Report "Fatal error" when it happens in the compiler log.
Instead of crashing.
E.g.
```
@react.component
let make:_ = () =>
```

produces

```
Fatal error: exception Invalid_argument("react.component calls cannot be destructured.")
```